### ISSUE TITLE
Broken entrypoint name format 

### ISSUE THREAD

**Issue by worthless443** [gera2ld/json-server.py#1]
The entrypoint name is in an invalid format that python setup tools doesn't like.  The name is `json-server.cli:main` format where the char `-` is not supported in python (it should have been like `json_server.cli:main` or `json.server.cli:main`, I guess).

This has broken my entire setup envoirment. 
```Python
 File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pkg_resources\__init__.py", line 2472, in parse
    raise ValueError(msg, src)
ValueError: ("EntryPoint must be in 'name=module:attrs [extras]' format but got this instead json-server=json-server.cli:main", 'json-server=json-server.cli:main')
```

**Comment by gera2ld** [comment]
fixed in 9993496
