### ISSUE TITLE
How to use the server on client side ?

### ISSUE THREAD

**Issue by AureliusMarcusHu** [gera2ld/json-server.py#10]
Hi, 
I don't understand the sense of this json sever if there is no client side.
If I understand correcty, the server load a json file and run forever or until you close the server, is this correct ?
But then, how you connect to this running server and get the whole data or pieces of the data from this server ?
Can sombody explain this ?

Kind regards.

**Comment by gera2ld** [comment]
It is a super lite (mock) API server for frontend developers, so you can easily start development with RESTful APIs by providing a data file with mock data.
I believe there are already examples in README showing how to get data from the server.
You may be in the wrong place if you are not a developer.

**Comment by AureliusMarcusHu** [comment]
Hi Gerald,

I had little or no experience with the 'curl' tool. But after some experimentation, I'm pretty good with it now.
Now I am using json-server for a completely different purpose than suggested on your home site.
I mainly use the server to share configuration data between the different modules in my python project.
Finally done with loading the same or different files a hundred times. The configuration data of my project differ from day to day. In the morning the data will be configured for the day and stored it in a file 'server_data.json' . After  your json-server will be started with this data. It runs 15 hours a day and is very stable and fast. Part of this data are the indexes of data-files and folders in my project, something anyone can use. Finding and loading a data-file is now a piece of cake in any module off the project. One minor, it's a pity that you can't add a new key in runtime, then the server is in trouble. Nevertheless, I would like to express my gratitude for this extraordinary fast and stable lightweight tool, It only uses 20.5 MB including my data. Timing: between 10 and 20 ms per call depending on the size of the called data. Thanks a lot for sharing this tool.

P.S. For those interested, I would be happy to help with the python-code for sharing data by this server.

**Comment by gera2ld** [comment]
Thanks for your feedback.

I think a WebDAV server might be better for your case, e.g. [rclone serve webdav](https://rclone.org/commands/rclone_serve_webdav/), [dave](https://github.com/micromata/dave).

It is a good idea to support adding new keys at runtime, maybe I'll support it in the future.
