### ISSUE TITLE
error on server start

### ISSUE THREAD

**Issue by aurelben** [gera2ld/json-server.py#3]
Hi 

I installed it with pipx as recomended
when I try to send a request on the serveur I got this error 

`INFO:aiohttp.server:JSON Server v0.1.7/CPython 3.8.2 - by Gerald
====================
Local:  http://[::1]:3000
---
Local:  http://localhost:3000
Remote: http://51.77.206.90:3000
====================
ERROR:asyncio:Exception in callback StreamReaderProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle StreamReaderProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/asyncio/streams.py", line 260, in connection_made
    res = self._client_connected_cb(reader,
TypeError: __call__() takes 2 positional arguments but 3 were given
ERROR:asyncio:Exception in callback StreamReaderProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle StreamReaderProtocol.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/asyncio/streams.py", line 260, in connection_made
    res = self._client_connected_cb(reader,
TypeError: __call__() takes 2 positional arguments but 3 were given
`
Thanks a lot for your work

**Comment by gera2ld** [comment]
Sorry, my bad.

Please upgrade to v0.1.8 with `pipx upgrade json-server.py`.
