### ISSUE TITLE
update db with post

### ISSUE THREAD

**Issue by cesarmarinhorj** [gera2ld/json-server.py#5]
when send a post request, data is not appended in json file.
can write an example, with requests?

**Comment by gera2ld** [comment]
First create a `db.json` file with content that reflects your data structure, for example:

```json
{
  "posts": []
}
```

Then start server with `json-server db.json`.

Create a post:

```sh
$ curl -H 'content-type: application/json' -d '{"content":"blablabla"}' http://localhost:3000/posts
```

List all posts:

```sh
$ curl http://localhost:3000/posts
```

**Comment by gera2ld** [comment]
Also updated in README.
